# docker run -it -d --name test1 -v ~/Desktop/harris/deepsignnet_v1:/tf/notebooks -p 8081:8888 tensorflow/tensorflow:1.14.0-gpu-py3-jupyter
version: '3.8'

services:
  test1:
    image: "tensorflow/tensorflow:1.14.0-gpu-py3-jupyter"
    restart: unless-stopped    
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all     
    volumes:
      - ~/Desktop/harris/deepsignnet_v1:/tf/notebooks
    ports:
      - 8081:8888
